# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d669f2149059a14f9ba6bcd9a7d46d4a85f3ff8d1b0c00750e4dd065df232377e7ae9b0433d2d0fe39faac577a954182177f79e103a9f3b1600150495eb801dd

test:
  secret_key_base: 8d71d68be142e329f28213e9787f4957892c241f0c4bffabce700e74a981a42e2ebf7884557c2ae1a11b0a7470ac5d38fc2621c54bca79172f7171022992e2b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
